import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local'


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const manrope = localFont({
  src: [
    {
      path: '../public/fonts/Manrope-VariableFont_wght.ttf',
    },
  ],
  variable: '--font-manrope',
})

const chakra = localFont({
  src: [
    {
      path: '../public/fonts/chakra/ChakraPetch-Bold.ttf',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../public/fonts/chakra/ChakraPetch-SemiBold.ttf',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../public/fonts/chakra/ChakraPetch-Medium.ttf',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../public/fonts/chakra/ChakraPetch-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/fonts/chakra/ChakraPetch-Light.ttf',
      weight: '300',
      style: 'normal',
    }

  ],
  variable: '--font-chakra',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${manrope.variable} ${chakra.variable}  antialiased flex w-screen  bg-[#09090C] overflow-x-hidden z-10 `}>
        {children}
      </body>
    </html>
  );
}
