import type { Metadata, Viewport } from "next";
import "./globals.css";
import localFont from 'next/font/local'
import LenisWrapper from "@/src/components/lenis/LenisWrapper"
import MainLayout from "@/src/components/screen-layout/MainLayout"


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  viewportFit: 'cover',
};

const manrope = localFont({
  src: [
    {
      path: '../public/fonts/Manrope-VariableFont_wght.ttf',
    },
  ],
  variable: '--font-manrope',
})

const chakra = localFont({
  src: [
    {
      path: '../public/fonts/chakra/ChakraPetch-Bold.ttf',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../public/fonts/chakra/ChakraPetch-SemiBold.ttf',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../public/fonts/chakra/ChakraPetch-Medium.ttf',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../public/fonts/chakra/ChakraPetch-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/fonts/chakra/ChakraPetch-Light.ttf',
      weight: '300',
      style: 'normal',
    }

  ],
  variable: '--font-chakra',
})

const elgoc = localFont({
  src: [
    {
      path: '../public/fonts/elgoc/Elgoc-Thin.otf',
      weight: '200',
      style: 'normal',
    },
    {
      path: '../public/fonts/elgoc/Elgoc-DEMO-Light.otf',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../public/fonts/elgoc/Elgoc-DEMO-Regular.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/fonts/elgoc/Elgoc-Medium.otf',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../public/fonts/elgoc/Elgoc-DEMO-SemiBold.otf',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../public/fonts/elgoc/Elgoc-DEMO-Bold.otf',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../public/fonts/elgoc/Elgoc-Black.otf',
      weight: '900',
      style: 'normal',
    },
  ],
  variable: '--font-elgoc',
})
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"
          />
      </head>
      <body className={`${manrope.variable} ${chakra.variable} ${elgoc.variable}  antialiased relative flex w-lvw h-lvh bg-neutral-950 `}>
        <LenisWrapper />
        <MainLayout />
        
        {children}
      </body>
    </html>
  );
}
